### ISSUE TITLE
little keyboard and warning from GooglePlay

### ISSUE THREAD

**Issue by dozheiny** [adibfara/Faradle#1]
Hi , I like this project and I think you can improve this project;
I found 2 problems in first try:

1. **warning from GooglePlay**
  when I installing app, I receive warning from google play for a threat app! anyway I install in Samsung A52 but in Xiaomi Redmi note 10 can't install app.

2. **Tiny keyboard**
  the keyboard is so little, seriously it's so little :)

please fix this problems
thanks 💓

**Comment by adibfara** [comment]
The warning is due to the fact that is not in the Play Store.

The keyboard has been updated :)
